services:
  gameserver:
    image: ghcr.io/nwerosama/farmsim-docker:fs25
    container_name: fs25-server
    restart: unless-stopped
    environment:
      - VNC_PORT=5900
      - VNC_PASSWORD=vnc_pw
      - PUID=1000
      - PGID=1000
      - WEB_USERNAME=admin
      - WEB_PASSWORD=admin_pw
      - WEB_PORT=8080
      - GAME_PORT=10823
      - GAME_NAME=Dedi Server
      - AUTOSTART_ENABLED=false # Required else your container will immediately exit.
                                # You can set it to true if you like Supervisor to
                                # launch the webui and game when container starts
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/fs25/docs:/opt/fs25/docs
      - '/opt/fs25/game:/home/nobody/.fs_server/drive_c/Program Files (x86)/Farming Simulator 2025'
      - /opt/fs25/dlc:/opt/fs25/dlc
      - /opt/fs25/install:/opt/fs25/install
      - '/opt/fs25/crshdmp:/home/nobody/.fs_server/drive_c/users/nobody/AppData/Local/GIANTS Crash Reporter'
    ports:
      # host:container
      - 5900:5900/tcp                 # VNC
      - 8080:${WEB_PORT:-8080}/tcp    # Webinterface
      - 10823:${GAME_PORT:-10823}/udp # Game (UDP)
      - 10823:${GAME_PORT:-10823}/tcp # Game <--> GIANTS (from what I'm told anyway)
    cap_add:
      - SYS_NICE
