[program:xvfb]
priority=0
user=root
command=bash -c "exec /usr/bin/Xvfb :1 -screen 0 640x480x16"
stopsignal=KILL

[program:webserver]
priority=1
user=nobody
directory=/home/nobody
command=/bin/bash -c '/home/nobody/start_webserver.sh'
stopsignal=KILL
stopasgroup=true
killasgroup=true
autostart=%(ENV_AUTOSTART_ENABLED)s
autorestart=false
environment=HOME="/home/nobody",USER="nobody"

[program:gameserver]
priority=1
user=nobody
directory=/home/nobody
command=/bin/bash -c '/home/nobody/start_gameserver.sh'
stopsignal=KILL
stopasgroup=true
killasgroup=true
autostart=%(ENV_AUTOSTART_ENABLED)s
autorestart=false
environment=HOME="/home/nobody",USER="nobody"
