[program:xvfb]
priority=0
user=root
command=bash -c "exec /usr/bin/Xvfb :1 -screen 0 640x480x16"
stopsignal=KILL

# i fricking hate Docker volume mounts
[program:fix_ownership]
priority=0
user=root
command=chown -R nobody:users /home/nobody
autostart=true
autorestart=false
startsecs=0

[program:webserver]
priority=1
user=nobody
directory=/home/nobody
command=/bin/bash -c '/home/nobody/start_webserver.sh'
stopsignal=KILL
stopasgroup=true
killasgroup=true
autostart=%(ENV_AUTOSTART_ENABLED)s
autorestart=false
environment=HOME="/home/nobody",USER="nobody"

[program:gameserver]
priority=1
user=nobody
directory=/home/nobody
command=/bin/bash -c '/home/nobody/start_gameserver.sh'
stopsignal=KILL
stopasgroup=true
killasgroup=true
autostart=%(ENV_AUTOSTART_ENABLED)s
autorestart=false
startsecs=5
environment=HOME="/home/nobody",USER="nobody"
